square-root/coef-style

- assets/stylesheets/coefficient/sidebar.sass
- assets/stylesheets/coefficient/topnav.sass
- localdev/companyprofilepublic.html.ejs
- localdev/locationspublic.html.ejs
- localdev/myprofilepublic.html.ejs
- localdev/profile-sidebar.html.ejs
- localdev/wp-sidebar.html.ejs
* Fixing top nav logo
* Updating social links markup
* Removing left nav search
> CF-162: Template cleanup

- assets/stylesheets/coefficient/aside.sass
- assets/stylesheets/coefficient/typography.sass
- localdev/homepage.html.ejs
This commit adds in some examples of different formatting that
needs to be available as well as updates some of the styling for
header elements.
> CF-288: Minor updates to notes styling

- assets/javascripts/coefficient/general.js
- assets/stylesheets/coefficient/froala.sass
- assets/stylesheets/coefficient/main.scss
- assets/stylesheets/coefficient/notes.sass
- localdev/homepage.html.ejs
This commit adds styles for notes that are in a completley new
state.
> CF-288: Add styles for 'new' note

- assets/stylesheets/coefficient/profiles.sass
This commit changes the cursor to a pointer when hovering over
the profile and store picture.
> CF-325: Make cursor change to pointer to indicate actionable

- localdev/homepage.html.ejs
This commit adds the default bootstrap datepicker style call back
into the homepage.
> CF-353: Add bootstrap datepicker styles

- assets/stylesheets/coefficient/layout.sass
- assets/stylesheets/coefficient/main.scss
- assets/stylesheets/coefficient/print.sass
This commit adds a print specific stylesheet for default browser
print styles.
> CF-370: Print styling

- assets/stylesheets/coefficient/action-items.sass
- assets/stylesheets/coefficient/dropdown-menu.sass
- assets/stylesheets/coefficient/global-search.sass
- assets/stylesheets/coefficient/lists.sass
- assets/stylesheets/coefficient/main.scss
- assets/stylesheets/coefficient/notes.sass
- localdev/header.html.ejs
- localdev/homepage.html.ejs
This commit adds markup and styling for list of item actions in note
view. Includes user popovers.
> CF-285: Add markup for action items view

- localdev/locationspublic.html.ejs
This commit adds the markup for the action header to show a button
to activate or deactivate a location based on current status.
> CF-316: Markup for activating/deactivating locations

- localdev/header.html.ejs
- localdev/locations-sidebar.html.ejs
- localdev/locationspublic.html.ejs
This commit adds the location profile markup.
> CF-375: Add location profile view markup

- assets/stylesheets/coefficient/action-items.sass
- localdev/companyprofile.html.ejs
- localdev/homepage.html.ejs
- localdev/locations.html.ejs
- localdev/locationspublic.html.ejs
- localdev/myprofile.html.ejs
- localdev/myprofilepublic.html.ejs
This commit is for all of the items that came from the 5/8 design
review for action items and user/location profile.
> CF-423: Design review updates

- assets/stylesheets/coefficient/action-items.sass
- assets/stylesheets/coefficient/main.scss
- assets/stylesheets/coefficient/tabs.sass
- localdev/actionitems.html.ejs
- localdev/actionitemscompleted.html.ejs
This commit contains the action items full page including markup
for new tabs component.
> CF-373: Action items markup and styling

- assets/stylesheets/coefficient/buttons.sass
- assets/stylesheets/coefficient/forms.sass
- assets/stylesheets/coefficient/labels-badges.sass
- assets/stylesheets/coefficient/layout.sass
- assets/stylesheets/coefficient/main.scss
- assets/stylesheets/coefficient/profiles.sass
- assets/stylesheets/coefficient/slideout.sass
- assets/stylesheets/coefficient/tags.sass
- localdev/myprofilepublic.html.ejs
- localdev/users.html.ejs
This commit includes markup for the following:
- CF-389: Slideout with admin permissions; user badge
- CF-379: Roles dropdown and subsequent form optiosn in slideout
- CF-380: Location assignment for Field and Location user roles
> CF-335: Markup for roles and permission for users

- assets/stylesheets/coefficient/forms.sass
- assets/stylesheets/coefficient/profiles.sass
- assets/stylesheets/coefficient/slideout.sass
- localdev/header.html.ejs
- localdev/locationsadmin.html.ejs
- localdev/locationspublic.html.ejs
This commit moves the activate/deactivate location to the slideout
along with ability to update location details when location is
clicked in table.
> CF-436: Location slideout markup

- assets/stylesheets/coefficient/notes.sass
This commit adds some extra styling around the location selector once
it is in focus.
> CF-457: Update styling for location selector

- localdev/error.html.ejs
This commit adds markup for a general error page when a page does
not exist.
> CF-420: Error page

- assets/javascripts/localdev/general.js
- assets/stylesheets/coefficient/audits.sass
- assets/stylesheets/coefficient/buttons.sass
- assets/stylesheets/coefficient/forms.sass
- assets/stylesheets/coefficient/layout.sass
- assets/stylesheets/coefficient/main.scss
- assets/stylesheets/coefficient/notes.sass
- assets/stylesheets/coefficient/progress-bars.sass
- assets/stylesheets/coefficient/sidebar.sass
- assets/stylesheets/coefficient/tabs.sass
- assets/stylesheets/coefficient/typography.sass
- localdev/auditreport.html.ejs
- localdev/audits.html.ejs
- localdev/auditscompleted.html.ejs
- localdev/header.html.ejs
- localdev/myprofilepublic.html.ejs
- localdev/newaudit.html.ejs
- localdev/notes-sidebar.html.ejs
- localdev/pages-blank-header.html.ejs
- localdev/pages-blank.html.ejs
- localdev/profile-sidebar.html.ejs
- localdev/roles.html.ejs
This commit contains markup and styling for creating, viewing and
listing audits.
> CF-391: Create, View, List Audit

- assets/stylesheets/coefficient/layout.sass
- assets/stylesheets/coefficient/slideout.sass
- localdev/actionitems.html.ejs
- localdev/actionitemscompleted.html.ejs
- localdev/homepage.html.ejs
- localdev/locationsadmin.html.ejs
- localdev/myprofilepublic.html.ejs
- localdev/users.html.ejs
This commit updates the slideout markup to what is being used after
development of component.
> CF-316: Update slideout component markup

- assets/stylesheets/coefficient/responsive.sass
This commit fixes responsive styling to handle tablet and mobile
sizes to handle the fixed page headers.
> CF-516: Add responsive styling for fixed header

- assets/stylesheets/coefficient/main.scss
- assets/stylesheets/coefficient/overlay.sass
- localdev/homepage.html.ejs
This commit adds styling for an overlay component that can be used
elsewhere as well.
> CF-318: Loading overlay markup

- assets/stylesheets/coefficient/slideout.sass
- localdev/homepage.html.ejs
This commit adds the animation for the slide out and slide in
transitions on the slideout component.
> CF-500: Add slideout/slidein transitions

- assets/stylesheets/coefficient/action-items.sass
- localdev/homepage.html.ejs
This commit contains the markup and styling for the slideout of
a completed aciton item.
> CF-485: Completed action item slideout markup

- assets/javascripts/localdev/general.js
- assets/stylesheets/coefficient/layout.sass
- assets/stylesheets/coefficient/responsive.sass
- localdev/actionitems.html.ejs
- localdev/actionitemscompleted.html.ejs
- localdev/locationsadmin.html.ejs
- localdev/myprofilepublic.html.ejs
- localdev/users.html.ejs
Updating the fixed action header position solution to use CSS instead of JS.
> CF-581: Fixed Action Header Positioning

- assets/stylesheets/coefficient/contacts-list.sass
- assets/stylesheets/coefficient/main.scss
- localdev/locationspublic.html.ejs
Add contacts list for locations and users for a location profile
page.
> CF-435 CF-434: Add locations and user contacts list

- assets/stylesheets/coefficient/contacts-list.sass
- localdev/locationspublic.html.ejs
- localdev/myprofilepublic.html.ejs
This commit adds a locations list to the profile view. The list markup
has also been genericized to work for both user lists and location
lists.
> CF-434: Add locations to user profile view

- assets/stylesheets/coefficient/action-items.sass
- assets/stylesheets/coefficient/contacts-list.sass
- assets/stylesheets/coefficient/lists.sass
- assets/stylesheets/coefficient/tables.sass
- localdev/locationspublic.html.ejs
- localdev/myprofilepublic.html.ejs
This commit adds a light blue hover background for action items and
contact list items to indicate that they can be clicked.
> CF-590: Add hover bg to indicate clickable areas

- assets/stylesheets/coefficient/profiles.sass
- assets/stylesheets/coefficient/topnav.sass
Styling for accommodating for white background for top nav
> CF-576: Accommodating white bg for top navigation

- assets/stylesheets/coefficient/action-items.sass
- assets/stylesheets/coefficient/profiles.sass
- assets/stylesheets/coefficient/responsive.sass
- assets/stylesheets/coefficient/sidebar.sass
- assets/stylesheets/coefficient/topnav.sass
Centering thumbnail photos vertically and horizontally.
> CF-580: Centering thumbnail photos

- assets/stylesheets/coefficient/aside.sass
- assets/stylesheets/coefficient/audits.sass
- assets/stylesheets/coefficient/buttons.sass
- assets/stylesheets/coefficient/froala.sass
- assets/stylesheets/coefficient/profiles.sass
- localdev/audit.html.ejs
- localdev/auditscompleted.html.ejs
- localdev/fieldaudits.html.ejs
- localdev/fieldauditscompleted.html.ejs
- localdev/fom-sidebar.html.ejs
- localdev/header.html.ejs
Markup and styling for audits in the context of a field user
> CF-588: Field user audit views

- assets/stylesheets/coefficient/responsive.sass
Fix styling of container when view has both a sidebar and an aside
in tablet size.
> CF: 581: Minor responsive fix

- assets/stylesheets/coefficient/topnav.sass
Safari requires webkit specific property for 'tranform'
> CF-615: Add webkit, MS specific 'transform' property

- assets/stylesheets/coefficient/colors.sass
- assets/stylesheets/coefficient/helpers.sass
- assets/stylesheets/coefficient/topnav.sass
- localdev/header.html.ejs
Removing a lot of the unnecessary bloat from topnav.sass file for
a cleaner solution. Also converting block of code to middle align
things to a mixin for future use.
> CF-302: Refactor topnav.sass

- assets/stylesheets/coefficient/attachments.sass
- assets/stylesheets/coefficient/audits.sass
- assets/stylesheets/coefficient/lists.sass
- assets/stylesheets/coefficient/main.scss
- assets/stylesheets/coefficient/notes.sass
- localdev/audit.html.ejs
This commit contains markup and styling for comments and attachments
for both view and submit on audits for field users.
> CF-431 CF-612: Comment and attachments for audits

- assets/stylesheets/coefficient/notes.sass
Temporarily removing Froala for rich text editing so adding some temporary styling for regular text inputs.
> CF-585: Styling for non rich text note

- assets/stylesheets/coefficient/helpers.sass
- assets/stylesheets/coefficient/notes.sass
This commit adds styling for disabled and readonly states for the notes views.
> CF-585: Styling for non-rich text notes

- assets/stylesheets/coefficient/audit-reporting.sass
- assets/stylesheets/coefficient/audits.sass
- assets/stylesheets/coefficient/buttons.sass
- assets/stylesheets/coefficient/contacts-list.sass
- assets/stylesheets/coefficient/main.scss
- localdev/auditnotreported.html.ejs
- localdev/auditreport.html.ejs
Adding reporting table hierarchy and 'not reported' section markup for audit reporting.
> CF-610: Audit monthly reporting option markup

- assets/stylesheets/coefficient/styleguide.sass
- localdev/index.html.ejs
- localdev/package.json
Implementing Scrollspy for styleguide navigation fanciness
> CF-480: Styleguide improvements

- assets/stylesheets/coefficient/audits.sass
- assets/stylesheets/coefficient/notes.sass
- assets/stylesheets/coefficient/print.sass
Styling to hide audit and note text area and show plaintext isntead
for print purposes only.
> CF-606: Print styling

- assets/stylesheets/coefficient/audits.sass
- assets/stylesheets/coefficient/buttons.sass
- assets/stylesheets/coefficient/forms.sass
- assets/stylesheets/coefficient/notes.sass
CF-727: Remove extra 'readonly' styles
> CF-727: Remove 'not allowed' cursor for disabled form fields

- assets/stylesheets/coefficient/buttons.sass
For when a button should be disabled without looking disabled
> CF-760: Update disabled button styling

- assets/stylesheets/coefficient/audits.sass
- assets/stylesheets/coefficient/profiles.sass
- localdev/audit.html.ejs
- Remove slider for comment/attachment
- Add expand/collapse section for comment/attachment
- Print suport
> CF-612: Update markup for audit view

- assets/stylesheets/coefficient/audits.sass
- assets/stylesheets/coefficient/print.sass
- assets/stylesheets/coefficient/responsive.sass
* Placeholder styling
* Expand/collapse bar styling
* 'fixed header' responsive styling fix
> CF-824: Field audit styling tweaks

- assets/stylesheets/coefficient/layout/aside.sass
- assets/stylesheets/coefficient/layout/responsive.sass
- assets/stylesheets/coefficient/layout/sidebar.sass
- assets/stylesheets/coefficient/layout/topnav.sass
- assets/stylesheets/coefficient/modules/notes.sass
- assets/stylesheets/coefficient/typography.sass
- assets/stylesheets/coefficient/utilities/dropdown-menu.sass
- assets/stylesheets/coefficient/utilities/slideout.sass
- assets/stylesheets/coefficient/utilities/tables.sass
Refactoring responsive.sass file as well as cleaning up some of the
responsive styling for the main layouts of the application:
- top navigation
- left sidebar
- aside
> CF-853: Refactor responsive.sass

- assets/stylesheets/coefficient/helpers.sass
- assets/stylesheets/coefficient/layout/aside.sass
- assets/stylesheets/coefficient/layout/layout.sass
- assets/stylesheets/coefficient/layout/page-title.sass
- assets/stylesheets/coefficient/layout/responsive.sass
- assets/stylesheets/coefficient/modules/audits.sass
- assets/stylesheets/coefficient/modules/notes.sass
- assets/stylesheets/coefficient/utilities/buttons.sass
Reverts square-root/coef-style#206
> Revert "CF-1108: Update styles for new header component"
